name: 王英博

url: http://www.doubleia.io

baseurl: ""

paginate: 5

avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

markdown: redcarpet
highlighter: pygments
permalink: /:title/

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
